apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-test
  template:
    metadata:
      labels:
        app: web-test
    spec:
      containers:
      - name: web-test
        image: ghcr.io/zaszasxs/web-test:sha-4f6b6daef801b19e22a9c2ac6936a0eeb5b4f1b7
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-test-svc
spec:
  selector:
    app: web-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
